openai:
  # Default: GPT-3.5 with the text completion API
  model: text-davinci-003
  endpoint: completions
  # ChatGPT
  # model: gpt-3.5-turbo
  # endpoint: chat
  # GPT-4
  # model: gpt-4
  # endpoint: chat